name: Build APK

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch.
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies that the job should run on the latest Ubuntu runner.

    steps:
    - uses: actions/checkout@v2
      # This step checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      # This step sets up Python 3.9 for use in actions by downloading, caching, and configuring the environment.

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libjpeg8-dev
        pip install cython==0.29.19
        pip install buildozer
      # This step installs required packages and libraries that Buildozer needs to compile the APK.

    - name: Build APK
      run: |
        buildozer init
        # If you already have a buildozer.spec file, you don't need to run `buildozer init` unless you want to overwrite it with a new one.
        buildozer -v android debug
      # This step executes Buildozer to compile the APK. The `-v` flag enables verbose output to help diagnose issues.

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: bin/*.apk
      # This step uploads the generated APK as an artifact, which can be downloaded from the GitHub Actions workflow run page.

    - name: Clean up Post Build
      if: always()
      run: |
        buildozer android clean
      # Optional: Clean up any build files to free space on the runner.
