name: Build Android APK

on:
  push:
    branches:
      - master  # Ensures this runs on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v2
      # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      # This step specifically sets up Python 3.9 to avoid issues with distutils.

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libjpeg8-dev
      # Installs necessary Ubuntu packages for building the app.

    - name: Install Python dependencies
      run: |
        pip install cython==0.29.19
        pip install buildozer
      # Installs required Python packages, including Buildozer and Cython.

    - name: Build APK
      run: |
        buildozer -v android debug
      # Executes Buildozer to compile the APK with verbose output to help diagnose issues.

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: bin/*.apk
      # Uploads the generated APK as an artifact, which can be downloaded from the GitHub Actions workflow run page.
